/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author st49651
 */
public class NewJFrame extends javax.swing.JFrame {

    private int vysledek;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.vysledek = 0;
        jButtonAno2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabelHlavniText = new javax.swing.JLabel();
        jButtonMinus = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jCheckBoxPoDvou = new javax.swing.JCheckBox();
        jSpinnerStep = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButtonAno1 = new javax.swing.JButton();
        jButtonNe = new javax.swing.JButton();
        jButtonAno2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHlavniText.setText("0");
        getContentPane().add(jLabelHlavniText, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 116, -1, -1));

        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 148, -1, -1));

        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 75, -1, -1));

        jCheckBoxPoDvou.setText("po dvou?");
        getContentPane().add(jCheckBoxPoDvou, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 25, -1, -1));

        jSpinnerStep.setMaximumSize(new java.awt.Dimension(10, 10));
        getContentPane().add(jSpinnerStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 26, 105, -1));

        jLabel1.setText("Dokončím počítačovou grafiku?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 243, -1, -1));

        jButtonAno1.setText("ANO");
        jButtonAno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAno1MouseEntered(evt);
            }
        });
        jButtonAno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAno1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 291, -1, -1));

        jButtonNe.setText("NE");
        jButtonNe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNe, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 291, -1, -1));

        jButtonAno2.setText("ANO");
        jButtonAno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAno2MouseEntered(evt);
            }
        });
        getContentPane().add(jButtonAno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 291, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        if(jCheckBoxPoDvou.isSelected())
            vysledek += 2;
        else
            vysledek += (int) jSpinnerStep.getValue();
        updateValue();        
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        if(jCheckBoxPoDvou.isSelected())
            vysledek -= 2;
        else
            vysledek -= (int) jSpinnerStep.getValue();
        updateValue(); 
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonAno1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAno1MouseEntered
        jButtonAno1.setVisible(false);
        jButtonAno2.setVisible(true);
    }//GEN-LAST:event_jButtonAno1MouseEntered

    private void jButtonAno2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAno2MouseEntered
        jButtonAno1.setVisible(true);
        jButtonAno2.setVisible(false);
    }//GEN-LAST:event_jButtonAno2MouseEntered

    private void jButtonNeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeActionPerformed
        jOptionPane1.showMessageDialog(this, "To nevadí, pristi rok taky sance");
    }//GEN-LAST:event_jButtonNeActionPerformed

    private void jButtonAno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAno1ActionPerformed
     
    private void updateValue(){
       String vypis;
       vypis = String.valueOf(vysledek);
       jLabelHlavniText.setText(vypis);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAno1;
    private javax.swing.JButton jButtonAno2;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonNe;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JCheckBox jCheckBoxPoDvou;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHlavniText;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JSpinner jSpinnerStep;
    // End of variables declaration//GEN-END:variables
}
